name: Sync labels
on:
  push:
    branches: [master]
    paths: [.github/labels.yml]
jobs:
  make-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1